package com.foodie.boundary2;

import com.foodie.model.Observer;

import javafx.fxml.FXML;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

public class ModeratoreView2Controller implements Observer{
	private static ModeratoreView2Controller istanza;
	@FXML
	private TextArea descrizioneTextArea;
	@FXML
	private Label usernameLabel;
	
	private ModeratoreView2Controller() {
	}
	
	public static synchronized ModeratoreView2Controller ottieniIstanza() {
		if(istanza == null) {
			istanza = new ModeratoreView2Controller();
		}
		return istanza;
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void tornaAlLogin(MouseEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void aggiornaView() {
		// TODO Auto-generated method stub
		
	}
}
